CREATE TABLE students (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  department VARCHAR2(100) NOT NULL,
  age NUMBER
);

INSERT INTO students (name, department, age) VALUES ('Arun', 'CSE', 21);
INSERT INTO students (name, department, age) VALUES ('Priya', 'ECE', 22);
INSERT INTO students (name, department, age) VALUES ('Kavin', 'IT', 21);

COMMIT;
